### ISSUE TITLE
Nil slices

### ISSUE THREAD

**Issue by morimotoyuuki111** [morimotoyuuki111/Go3#13]
```go
package main //パッケージを宣言

import "fmt"　//fmtパッケージをインポート

func main() {
  var s[]int　//varは定義  s[]を定義
  fmt.Println(s, len(s), cap(s))　 //s[]を出力。[]は空なので[]と出力される。len(s),cap(s)を出力。sは何も代入されていないため0
  
  if s == nil //もしもsの中が0だったらnil!と出力してねと意味
      fmt.Println("nil!")
  }
}
```
sは何も代入されていないため0と理解しているのですが合っていますか?

**Comment by totsumaru** [comment]
> sは何も代入されていないため0と理解しているのですが合っていますか?

ちょっとだけ違っていますが、解説しますので大丈夫です。

スライスのゼロ値は`nil`です。
"ゼロ"ではなく"空"のイメージです。
ゼロという数字すら入っていない空っぽです。

[ゼロ値]
string → ""
int → 0
slice([]intや[]string) → nil

スライスのゼロ値は`nil`ということを覚えておきましょう。
