### ISSUE TITLE
Map literals continuedについて

### ISSUE THREAD

**Issue by morimotoyuuki111** [morimotoyuuki111/Go3#21]
```go

package main

import "fmt"

type Vertex struct {
	Lat, Long float64
}

var m = map[string]Vertex{
	"Bell Labs": {40.68433, -74.39967},
	"Google":    {37.42202, -122.08408},
}

func main() {
	fmt.Println(m)
}

```
# 質問１<br>
上記のサンプルコードはstringを省略しているということでしょうか？

# 質問2 <br>
もし、mapに渡すトップレベルの型が単純な型名である場合は、<br>リテラルの要素から推定できますので、その型名を省略することができます。<br>とあるのですがトップレベルの型とはどういういった意味なのでしょうか？

**Comment by totsumaru** [comment]
↑のコメントですが、シャープ`#`の後に大文字のスペースが入っているためマークダウンが機能していません。
修正してレイアウトを綺麗にしておきましょう！

**Comment by morimotoyuuki111** [comment]
申し訳ありません。只今、修正しました！

**Comment by totsumaru** [comment]
## 質問1の回答

stringは省略していません！
基礎のmapの書き方はこのような感じです。
"省略"については質問2で回答しますね。

```go
package main

import "fmt"

func main() {
	m := map[string]int{
		"a": 1,
		"b": 2,
	}

	fmt.Println(m["a"]) // 1
	fmt.Println(m["b"]) // 2
}
```

## 質問2の回答

今までは自分で作った型（構造体）を使うときは「型名{}」としなければなりませんでした。
しかし、Mapでは型があらかじめ指定されているので、省略して「{}」の書き方で記述できます。
今まで習ったやり方で書くと以下のようになります。
（以下の書き方でも間違いではないです）

```go
package main

import "fmt"

type Vertex struct {
	Lat, Long float64
}

var m = map[string]Vertex{
	"Bell Labs": Vertex{40.68433, -74.39967},  // 普通だとVertexをつけなければいけない
	"Google":    Vertex{37.42202, -122.08408}, // 普通だとVertexをつけなければいけない
}

func main() {
	fmt.Println(m)
}
```
