### ISSUE TITLE
sliceについて

### ISSUE THREAD

**Issue by morimotoyuuki111** [morimotoyuuki111/Go3#9]
```go
package main //パッケージを宣言

import "fmt"　//fmtパッケージをインポート

func main() { 
  primes :=[6]int{2, 3, 5, 7, 11, 13} //変数primesの中に[6]int{2, 3, 5, 7, 11, 13}が代入
  
  var s []int = primes[1:4]　// varは定義　　変数sの中にprimes[1:4]が代入
  fmt.Println(s) 
}
[3 5 7]
```

上記のサンプサンプルコードの出力結果が[3 5 7]なのはprimes[1:4]を<br>抽出しているからで合っていますか?
上記のサンプルコードでいくと{2, 3, 5, 7, 11, 13} なので0が2,1が3,2が5,3が7,4が11,5が13のため<br>

**Comment by totsumaru** [comment]
その理解で合ってます！

```go
primes[1:4]
```
は、日本語に言い換えると、
```
配列primesの「1番目の前」から「4番目の前」を取得する
```
となります。

**Comment by morimotoyuuki111** [comment]
ありがとうざいます！
配列primesの「1番目の前」から「4番目の前」を取得はそのまま理解して大丈夫ですか？
それかスライスとして理解すれば良いですか?

**Comment by totsumaru** [comment]
Goにおいての定義

・配列 → `[6]string` のような、入る数が決まっているもの（固定長）
・スライス → `[]string` のような、入る数が無制限のもの（可変長）

構造は同じですが、上限が決まっているかどうかで、呼び方が変わります。

> 配列primesの「1番目の前」から「4番目の前」を取得はそのまま理解して大丈夫ですか？

暗記しておけばOKです。ただ、調べれば出てくるので、忘れても大丈夫です。

>それかスライスとして理解すれば良いですか?
```go
 var s []int = primes[1:4]
```
は、配列primesから取り出した値をスライスsに入れている、という理解で大丈夫です。
